version: '3'
    
services:
  traefik:
    # The official v2 Traefik docker image
    image: traefik:v2.4
    environment:
    - TZ=Asia/Shanghai
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
      - "443:443"
    restart: on-failure
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml
      - ./traefik/config:/traefik
      - ./traefik/log:/etc/traefik/log
    networks:
      em:
       ipv4_address: 10.0.0.2
      
  consul:
    image: consul:1.8.5
    volumes:
      - ./consul/data:/consul/data
      - ./consul/config:/consul/config
    ports:
      - "8300:8300/tcp"
      - "8301:8301/udp"
      - "8302:8302/udp"
      - "8500:8500/tcp"
      - "53:8600/udp"
    command: agent -server -ui -bootstrap-expect=1 -client=0.0.0.0
    restart: on-failure
    networks:
      em:
       ipv4_address: 10.0.0.3
       
networks:
 em:
  ipam:
   driver: default
   config:
    - subnet: "10.0.0.0/24"